<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue_2</name>
   <tag></tag>
   <elementGuidId>a19d7fbd-698b-420a-9328-8aff99dbfd3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@name='save'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#payment-method-buttons-container > button[name=&quot;save&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>587a4a68-266a-45ad-9cbd-27c4f557393d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7fc86c49-27b4-4cb1-b714-286f2ed23e18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>a4e6ae33-48ff-428a-bef9-216ad1e488a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-1 payment-method-next-step-button</value>
      <webElementGuid>6083bda2-e49b-4ecd-a945-2a9e428908f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>PaymentMethod.save()</value>
      <webElementGuid>7b132cfc-6c74-432c-8b15-9ef291e83fa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>e9cab3d8-050e-4adc-a8f4-6e8e4b11f6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-method-buttons-container&quot;)/button[@class=&quot;button-1 payment-method-next-step-button&quot;]</value>
      <webElementGuid>09cacffa-a6f9-4d5e-849b-92832ef9c540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@name='save'])[2]</value>
      <webElementGuid>a0e3a91a-4c7e-4dbb-997a-851066d9efa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='payment-method-buttons-container']/button</value>
      <webElementGuid>cde4633f-6887-4ade-8bab-76c0d63dd6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='«'])[3]/following::button[1]</value>
      <webElementGuid>4e9faf14-56fc-4a0f-afa5-5dcb29cdda1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay by credit / debit card'])[1]/following::button[1]</value>
      <webElementGuid>7984b20a-dacb-4e1f-bf22-c6baab01a55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment information'])[1]/preceding::button[1]</value>
      <webElementGuid>6b09778e-226d-4bd3-8f51-4c52dbb4911d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment is not required'])[1]/preceding::button[1]</value>
      <webElementGuid>7b0786da-4194-4ae6-966e-bfc5305aa4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div[2]/div/button</value>
      <webElementGuid>2ca063e3-18a1-4d74-915b-490687d5bae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @name = 'save' and (text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>51597e5f-d91f-410f-afdd-c3d8c1434571</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
