<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1,600.00_termsofservice</name>
   <tag></tag>
   <elementGuidId>95e82285-50d8-4801-b26d-a966ae701a7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#termsofservice</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termsofservice']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7bceaf9-6c8c-4433-bf22-3a30323a0649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termsofservice</value>
      <webElementGuid>bb6813bb-84ef-490d-9f01-f1f8f042016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>46769771-f06e-40d0-9931-3b540a516fb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termsofservice</value>
      <webElementGuid>17a1a1d0-dd95-48b9-af2f-da4ccd4b5f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termsofservice&quot;)</value>
      <webElementGuid>d320713c-cdf6-421b-9fdc-08d383890497</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termsofservice']</value>
      <webElementGuid>cce596c2-e937-4fc2-a01f-e2b097f299fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='shopping-cart-form']/div[3]/div[2]/div[3]/input</value>
      <webElementGuid>8716765d-d76f-4af8-a634-7f2ef4391e8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/input</value>
      <webElementGuid>01f8483d-2c44-44ff-963a-8cb419e5208c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termsofservice' and @type = 'checkbox' and @name = 'termsofservice']</value>
      <webElementGuid>c9338398-8a9b-4d48-bd44-563eab26812b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
